# Generated by Django 5.2.7 on 2025-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#bf7724', help_text='Color hex code of the project, e.g. #abcdef', max_length=7),
            preserve_default=False,
        ),
    ]
