# Generated by Django 5.2.7 on 2025-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
